# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  get_org_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Main Organization Name
        id: get_org_name
        run: |
          # Extract the repository owner from GITHUB_REPOSITORY
          IFS='/' read -ra REPO_INFO <<< "$GITHUB_REPOSITORY"
          OWNER="${REPO_INFO[0]}"

          # Get the main organization name from the user's profile
          MAIN_ORG=$(curl -s "https://api.github.com/users/$OWNER" | jq -r '.company')

          echo "MAIN_ORG_NAME=$MAIN_ORG" >> $GITHUB_ENV

      - name: Display Main Organization Name
        id: test-abc
        run: |
          echo "Main Organization Name: $MAIN_ORG_NAME"
